### ISSUE TITLE
How to output a full tree json

### ISSUE THREAD

**Issue by wemersonjanuario** [KristianAbrahamsen/tree-util#2]
Hello I have one select that returns rows like this and would like a tree json

Current Select

`[
    {
        "id": 1,
        "description": "Foods",
        "parent_id": null
    },
    {
        "id": 2,
        "description": "Drinks2",
        "parent_id": null
    },
    {
        "id": 3,
        "description": "Burguer",
        "parent_id": 1
    },
    {
        "id": 4,
        "description": "Juice",
        "parent_id": 2
    },
    {
        "id": 5,
        "description": "Barbecue",
        "parent_id": 3
    },
    {
        "id": 6,
        "description": "Grape",
        "parent_id": 4
    }
]`

How to build tree and return a JSON tree like this?

`[
  {
    "id": 1,
    "description": "Foods",
    "parent_id": null,
    "children": [
      {
        "id": 3,
        "description": "Burguer",
        "parent_id": 1,
        "children": [
          {
            "id": 5,
            "description": "Barbecue",
            "parent_id": 3,
            "leaf": true
          }
        ]
      }
    ]
  },
  {
    "id": 2,
    "description": "Drinks2",
    "parent_id": null,
    "children": [
      {
        "id": 4,
        "description": "Juice",
        "parent_id": 2,
        "children": [
          {
            "id": 6,
            "description": "Grape",
            "parent_id": 4,
            "leaf": true
          }
        ]
      }
    ]
  }
]`

Thank you

**Comment by KristianAbrahamsen** [comment]
Hello wemersonjanuario.
Sorry for late reply. 

There is no API function at the current moment which supports what you request. 
It could be an interesting feature to add later.
