### ISSUE TITLE
Create node doesn't work dynamically

### ISSUE THREAD

**Issue by dmitrijs-pavlovs-dev** [KristianAbrahamsen/tree-util#3]
Hello. Create node function on tree doesn't seem to work dynamically.
 
```JS
  const trees = tree_utils.buildTrees([{ id: "NewNode" }], {
    id: "id",
    parentid: "parentid",
  })
  trees[0].createNode({
    id: "AnotherNode",
    parentid: "NewNode",
  })
  console.log("Search", trees[0].getNodeById("AnotherNode"))
//Search undefined
```

Edit: Fixed the id property.

**Comment by KristianAbrahamsen** [comment]
Hello dayrim.

The problem with the code you are presenting is that the first parameter is valid. It lacks the properties "id" and "parentid".
Please see the example below:

// An array where the items has a parent child reference using id properties
var items = [{ id : 1 }, { id : 2, parentid : 1 }, { id : 3, parentid : 1 },
             { id : 4, parentid : 1 }, { id : 5, parentid : 3 }];

// Config object to set the id properties for the parent child relation
var standardConfig =  { id : 'id', parentid : 'parentid'};

// Creates an array of trees. For this example there will by only one tree
var trees = tree_util.buildTrees(items, standardConfig);

**Comment by dmitrijs-pavlovs-dev** [comment]
> Hello dayrim.
> 
> The problem with the code you are presenting is that the first parameter is valid. It lacks the properties "id" and "parentid".
> Please see the example below:
> 
> // An array where the items has a parent child reference using id properties
> var items = [{ id : 1 }, { id : 2, parentid : 1 }, { id : 3, parentid : 1 },
> { id : 4, parentid : 1 }, { id : 5, parentid : 3 }];
> 
> // Config object to set the id properties for the parent child relation
> var standardConfig = { id : 'id', parentid : 'parentid'};
> 
> // Creates an array of trees. For this example there will by only one tree
> var trees = tree_util.buildTrees(items, standardConfig);

Hello. This was a typo here in code that i wrote. My apologizies. In your example tree with all nodes is created on first initialization. What i am trying to do is to create a tree and then add nodes dynamically as needed. Upon expection i can see that the node is added as child of rootNode, but still search node by ID returns undefined. 
Here i added a reproduction repo https://codesandbox.io/s/great-mirzakhani-w3jxx?file=/src/index.js  to lillustrate the case.

**Comment by KristianAbrahamsen** [comment]
Hello dayrim. 
I have checked your codesandbox example and I think you have a valid point.
I will reopen the issue.

Thanks for your notification

**Comment by KristianAbrahamsen** [comment]
Hello dayrim.

This issue has now been fixed. 
Thanks for improving this package/repository.
