### ISSUE TITLE
Cannot read properties of undefined (reading 'getNodeById')

### ISSUE THREAD

**Issue by nimrod-ne** [KristianAbrahamsen/tree-util#9]
I'm using the library inside a React app component. I added the exact code from the example but i get an error:

`Cannot read properties of undefined (reading 'getNodeById')`

![image](https://user-images.githubusercontent.com/105358579/178496157-bb6f7504-c215-4091-96de-0f32f33deeea.png)

My code:

```
import treeUtil from 'tree-util';

const items = [
  { id: 1 },
  { id: 2, parentid: 1 },
  { id: 3, parentid: 1 },
  { id: 4, parentid: 1 },
  { id: 5, parentid: 3 },
];

const standardConfig = { id: 'id', parentid: 'parentid' };

const trees = treeUtil.buildTrees(items, standardConfig);
```

**Comment by KristianAbrahamsen** [comment]
Hello nimrod-me

When I run your code here, it works fine for me:

https://npm.runkit.com/tree-util

Could you try it again in that run-environment and maybe compare the differences with your environment?
